### PR TITLE
fix: error handling on browser creation

### LINKED ISSUE #12: Excessive error logging on iOS 14 beta
See enormous amount of these in console:
`2020-07-24 11:11:52.085719-0400 Project Blue[1321:345925] dnssd_clientstub DNSServiceProcessResult called with NULL DNSServiceRef
`

Likely needing to do some checks in processing results.

### PR DESCRIPTION
**Pull request by jfro**
fixes #12

### CODE REVIEW

**Review by jesdazrez — APPROVED** [review]

**Review by gabdube — APPROVED** [review]
don't nee anything that can go wrong

File: src/browser.rs [hunk 1]
```diff
@@ -422,6 +426,10 @@ impl DNSServiceBrowser {
                 Some(DNSServiceBrowser::reply_callback),
                 mut_void_ptr!(self),
             );
+            if r != ffi::kDNSServiceErr_NoError {
+                error!("DNSServiceBrowser error: {}", r);
+                return Err(DNSServiceError::ServiceError(r));
+            }
```
Comment (corwinderkatch) [inline src/browser.rs:432]: Minor nit pick – due to the "double negative" of "not no error", it might be more readable if we changed it to something like:

```
match r {
    ffi::kDNSServiceErr_NoError => Ok(()),
   _ => {
                 error!("DNSServiceBrowser error: {}", r);
                Err(DNSServiceError::ServiceError(r))
             }
}
```

**Review by corwinderkatch — APPROVED** [review]

File: src/browser.rs (hunk 1 above)
Comment (jfro) [reply src/browser.rs:432]: yeah not a bad idea
